api/urls.py
from django.conf.urls import url
from api import views

urlpatterns = [
    url(r'^query/(?P<material_id>\d+)$', views.query, name='query'),
]

visualization/urls.py
from django.conf.urls import url
from visualization import views

urlpatterns = [
    url(r'^$', views.MeterialList.as_view(), name='index'),
    url(r'^(?P<material_id>[0-9]+)/$', views.detail, name='detail'),
#    url(r'^$', views.index, name='index'),
]

viz_wiki/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^visualization/',
            include('visualization.urls', namespace='visualization')),
]

api/models.py
from django.db import models

# Create your models here.

visualization/models.py
from django.db import models

class Material(models.Model):
    sparql = models.TextField('SPARQL')
    title = models.CharField('タイトル', max_length=256)
    template = models.CharField('テンプレート', max_length=256)
    meta = models.TextField('メタ情報')

    def __str__(self):
        return self.title

class Sparql:

    def query(material):
        res = Sparql.perform_query(material.sparql)
        # print("=== {} ===".format(res))
        return res

    def perform_query(sparql):
        # print("=== {} ===".format(sparql))
        from SPARQLWrapper import SPARQLWrapper, JSON
        sw = SPARQLWrapper("http://ja.dbpedia.org/sparql")
        sw.setQuery(sparql)
        sw.setReturnFormat(JSON)
        result = sw.query().convert()
        return result

api/views.py
import json
import re
from collections import OrderedDict
from django.http import HttpResponse
from visualization.models import Material
from visualization.models import Sparql
from django.template.loader import get_template
from django.template import Template
from django.template import Context


def query(request, material_id):
    material = Material.objects.get(pk=material_id)
    res = Sparql.query(material)
    # print("$$$ {} $$$".format(res['results']['bindings']))
    meta = json.loads(material.meta)
    # print("$$$ {} $$$".format(meta))

    items = []
    for result in res['results']['bindings']:
        od = []
        for key, value in result.items():
            v = value['value']
            if key in meta['split_columns']:
                w = v.split('__')
                if w[0]:
                    v = w[0]

            # print("### {} ###".format(value['value']))
            od.append((key, v))
        items.append(OrderedDict(od))

    #template = get_template("api/{}.txt".format(material.template))
    template = Template(meta['comment_template'])
    ct = Context({ 'items': items, 'meta': meta })
    comment = template.render(ct)
    # comment = ""
    # print(comment)

    # print("$$$ {} $$$".format(meta))
    # print("$$$ {} $$$".format(items))
    # print("$$$ {} $$$".format(comment))
    data = OrderedDict([('meta', meta), ('comment', comment),('items', items)])
    return render_json_response(request, data)

def render_json_response(request, data, status=None):
    """response を JSON で返却"""
    json_str = json.dumps(data, ensure_ascii=False, indent=2)
    # print("$$$ {} $$$".format(json_str))
    callback = request.GET.get('callback')
    if not callback:
        callback = request.POST.get('callback')  # POSTでJSONPの場合
    if callback:
        json_str = "%s(%s)" % (callback, json_str)
        response = HttpResponse(json_str, content_type='application/javascript; charset=UTF-8', status=status)
    else:
        response = HttpResponse(json_str, content_type='application/json; charset=UTF-8', status=status)
    return response

def conv(s):
    cs = []
    for e in re.findall("&#x([0-9a-fA-F]+);", s):
        cs.append(chr(int(e, 16)))
    return "".join(cs)

visualization/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from visualization.models import Material
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.list import ListView

class MeterialList(ListView):
    context_object_name='materials'
    template_name='visualization/index.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        materials = Material.objects.order_by('id')
        self.object_list = materials
        context = self.get_context_data(object_list=self.object_list)
        return self.render_to_response(context)

def detail(request, material_id):
    material = get_object_or_404(Material, pk=material_id)
    template = "visualization/{}.html".format(material.template)
    return render(request, template, {'material': material})

visualization/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>{% block title %}Site Title{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.gif' %}">
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>


  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
          <div class="navbar-header">
              <a class="navbar-brand" href="{% url 'visualization:index' %}">
                  VizWiki
              </a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li class="active">
                      <a href="{% url 'visualization:index' %}">
                          トップ
                      </a>
                  </li>
              </ul>
          </div>
      </div>
  </nav>
  <div class="container">
    {% block content %}
    {{ content }}
    {% endblock %}

  </div>
  <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

visualization/templates/visualization/bar_chart_horizontal.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}WikiPedia 見える化プロジェクト{% endblock title %}

{% block extrahead %}
  <style type="text/css">
  <!-- body {
      padding-top: 70px;
  }

  .jumbotron {
      text-align: center;
  }

  .bar {
      fill: steelblue;
  }

  .bar:hover {
      fill: brown;
  }

  .barNum {
    font-size: 9pt;
    fill: #ffffff;
  }

  .barYaxis {
    font-size: 9pt;
    fill: #000000;
  }

  -->
  </style>
{% endblock %}

{% block content %}
  <div class="jumbotron">
      <h1>{{ material.title }}</h1>
      <p>WikiPedia 見える化プロジェクト</p>
  </div>

  <p id="comment"></p>

  <svg id="myGraph" width="1000px"></svg>

  <table id="list" class="table table-hover">
    <thead>
      <tr>
        <th>順位</th>
        <th id="head_unit1"></th>
        <th id="head_unit2"></th>
        <th id="head_sample"></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>

  <script src="https://d3js.org/d3.v3.min.js"></script>
  <script src="{% static 'js/bar_chart_horizontal.js' %}"></script>
{% endblock content %}

visualization/templates/visualization/index.html
{% extends "base.html" %}

{% block title %}WikiPedia 見える化プロジェクト{% endblock title %}

{% block extrahead %}
<style type="text/css">
    <!-- body {
        padding-top: 70px;
    }

    .jumbotron {
        text-align: center;
    }

    -->
</style>
{% endblock %}

{% block content %}
  <div class="jumbotron">
      <h1>WikiPedia<br>見える化プロジェクト</h1>
  </div>
  <table class="table table-hover">
      <thead>
          <tr>
              <th>No</th>
              <th>Title</th>
          </tr>
      </thead>
      <tbody>
      {% for mate in materials %}
          <tr>
              <td>{{ mate.id }}</td>
              <td><a href="{{ mate.id }}">{{ mate.title }}</a></td>
          </tr>
      {% endfor %}
      </tbody>
  </table>

  {% if is_paginated %}
  <nav aria-label="Page navigation">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><a href="#">&laquo;</a></li>
        {% endif %}
        {% for linkpage in page_obj.paginator.page_range %}
          {% ifequal linkpage page_obj.number %}
            <li  class="active"><a href="#">{{ linkpage }}</a></li>
          {% else %}
            <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
          {% endifequal %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><a href="#">&raquo;</a></li>
        {% endif %}
      </ul>
  </nav>
  {% endif %}
{% endblock content %}